package com.whaa.shop.product.application;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.baomidou.mybatisplus.extension.plugins.pagination.Page; import com.whaa.shop.common.api.PageResponse; import com.whaa.shop.common.exception.BusinessException; import com.whaa.shop.product.domain.*; import com.whaa.shop.product.infrastructure.*; import org.jsoup.Jsoup; import org.jsoup.safety.Safelist; import org.springframework.stereotype.Service; import java.time.LocalDateTime; import java.util.Collections; import java.util.List;
@Service public class ProductService {private final ProductMapper products;private final SkuMapper skus;public ProductService(ProductMapper p,SkuMapper s){products=p;skus=s;}
 public PageResponse<Product> page(long page,long size,String keyword,Long categoryId){String term=keyword==null?"":keyword.trim();var q=new LambdaQueryWrapper<Product>().eq(Product::getPublished,true).eq(categoryId!=null,Product::getCategoryId,categoryId).and(!term.isBlank(),w->w.like(Product::getName,term).or().like(Product::getSubtitle,term)).orderByDesc(Product::getCreatedAt);Page<Product> r=products.selectPage(Page.of(page,size),q);return new PageResponse<>(r.getRecords(),r.getTotal(),page,size);}
 public List<Product> weeklyPicks(Long categoryId){var q=new LambdaQueryWrapper<Product>().eq(Product::getPublished,true).eq(categoryId!=null,Product::getCategoryId,categoryId).last("LIMIT 100");return randomTake(products.selectList(q),8);}
 public List<Product> hotPicks(){var q=new LambdaQueryWrapper<Product>().eq(Product::getPublished,true).orderByDesc(Product::getSales).last("LIMIT 30");return randomTake(products.selectList(q),6);}
 public List<Product> newArrivals(){var q=new LambdaQueryWrapper<Product>().eq(Product::getPublished,true).orderByDesc(Product::getCreatedAt).last("LIMIT 30");return randomTake(products.selectList(q),4);}
 public PageResponse<Product> adminPage(long page,long size,String keyword){var q=new LambdaQueryWrapper<Product>().like(keyword!=null&&!keyword.isBlank(),Product::getName,keyword).orderByDesc(Product::getCreatedAt);Page<Product> r=products.selectPage(Page.of(page,size),q);return new PageResponse<>(r.getRecords(),r.getTotal(),page,size);}
 public Product detail(Long id){Product p=products.selectById(id);if(p==null||!Boolean.TRUE.equals(p.getPublished()))throw new BusinessException("商品不存在");return p;}
 public Product save(Product p){p.setDetailHtml(Jsoup.clean(p.getDetailHtml()==null?"":p.getDetailHtml(),Safelist.relaxed().addTags("table","thead","tbody","tr","th","td").addAttributes("img","src","alt").addProtocols("img","src","http","https")));if(p.getCreatedAt()==null)p.setCreatedAt(LocalDateTime.now());if(p.getId()==null)products.insert(p);else products.updateById(p);return p;}
 public Sku saveSku(Sku sku){if(sku.getProductId()==null||products.selectById(sku.getProductId())==null)throw new BusinessException("商品不存在");if(sku.getPrice()==null||sku.getStock()==null||sku.getStock()<0)throw new BusinessException("SKU价格和库存无效");if(sku.getEnabled()==null)sku.setEnabled(true);if(sku.getSpecJson()==null)sku.setSpecJson("{}");if(sku.getId()==null)skus.insert(sku);else skus.updateById(sku);return sku;}
 public java.util.List<Sku> skus(Long productId){return skus.selectList(new LambdaQueryWrapper<Sku>().eq(Sku::getProductId,productId).eq(Sku::getEnabled,true));}
 private List<Product> randomTake(List<Product> candidates,int size){Collections.shuffle(candidates);return candidates.stream().limit(size).toList();}}
