<script setup lang="ts">
import{onMounted,ref}from'vue';import{ElMessage,ElMessageBox,type UploadRequestOptions}from'element-plus';import{api,type ApiResponse}from'@whaashop/shared';
interface Knowledge{id:number;fileName:string;mimeType:string;status:string;errorMessage?:string;createdAt:string;updatedAt:string}
const rows=ref<Knowledge[]>([]),uploading=ref(false);
async function load(){rows.value=(await api.get<ApiResponse<Knowledge[]>>('/admin/knowledge')).data.data}
async function upload(o:UploadRequestOptions){uploading.value=true;const form=new FormData();form.append('file',o.file);try{await api.post('/admin/knowledge',form,{timeout:120000});ElMessage.success('文件已上传并完成索引');o.onSuccess({});await load()}catch(e){ElMessage.error((e as Error).message)}finally{uploading.value=false}}
async function reindex(id:number){await api.post(`/admin/knowledge/${id}/reindex`,null,{timeout:120000});ElMessage.success('重建完成');load()}
async function remove(id:number){await ElMessageBox.confirm('将同时删除 MinIO 文件和 Milvus 向量，确认继续？','删除知识文件');await api.delete(`/admin/knowledge/${id}`);ElMessage.success('已删除');load()}onMounted(load)
</script>
<template><div class="panel"><div class="toolbar"><div><h2>智能客服知识库</h2><p style="color:#7290a8">上传资料后自动解析、分块并写入 Milvus。</p></div><el-button type="primary" :loading="uploading" @click="load">刷新状态</el-button></div><el-upload drag :http-request="upload" :show-file-list="false" accept=".pdf,.docx,.txt,.md"><div style="font-size:16px;color:#1d6fba">拖拽或点击上传 PDF / DOCX / TXT / MD</div><small>单文件最大 10MB</small></el-upload><el-table :data="rows" style="margin-top:20px"><el-table-column prop="fileName" label="文件名" min-width="220"/><el-table-column prop="mimeType" label="类型"/><el-table-column label="处理状态"><template #default="s"><el-tag :type="s.row.status==='READY'?'success':s.row.status==='FAILED'?'danger':'warning'">{{s.row.status}}</el-tag></template></el-table-column><el-table-column prop="errorMessage" label="失败原因" show-overflow-tooltip/><el-table-column prop="updatedAt" label="更新时间" width="190"/><el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click="reindex(s.row.id)">重建</el-button><el-button link type="danger" @click="remove(s.row.id)">删除</el-button></template></el-table-column></el-table><el-empty v-if="!rows.length" description="尚未上传知识文件"/></div></template>
