<script setup lang="ts">
import{onMounted,reactive,ref,shallowRef}from'vue';import{QuillEditor}from'@vueup/vue-quill';import{ElMessage}from'element-plus';import{api,type ApiResponse,type Product}from'@whaashop/shared';
interface Page<T>{items:T[];total:number}interface Category{id:number;name:string}
const rows=ref<Product[]>([]),categories=ref<Category[]>([]),keyword=ref(''),dialog=ref(false),uploading=ref(false),uploadingRichImage=ref(false),mainImageInput=ref<HTMLInputElement>(),richImageInput=ref<HTMLInputElement>(),quill=shallowRef<any>(),page=ref(1),size=ref(20),total=ref(0),form=reactive<any>({});
const editorOptions={modules:{toolbar:{container:[[{header:[1,2,3,false]}],['bold','italic','underline','strike'],[{list:'ordered'},{list:'bullet'}],[{color:[]},{background:[]}],['blockquote','link','image'],['clean']],handlers:{image:chooseRichImage}}}};
const empty=()=>({id:undefined,name:'',subtitle:'',categoryId:undefined,mainImage:'',detailHtml:'<h2>商品亮点</h2><p>请输入商品详情。</p>',minPrice:0,sales:0,published:true,skuSpec:'{}',skuPrice:0,skuStock:0});
async function load(){const[p,c]=await Promise.all([api.get<ApiResponse<Page<Product>>>('/admin/products',{params:{keyword:keyword.value,page:page.value,size:size.value}}),api.get<ApiResponse<Category[]>>('/admin/categories')]);rows.value=p.data.data.items;total.value=p.data.data.total;categories.value=c.data.data}
function search(){page.value=1;load()}function edit(product?:Product){Object.assign(form,product??empty());dialog.value=true}
function chooseMainImage(){mainImageInput.value?.click()}
async function uploadMainImage(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){ElMessage.error('请选择 JPG、PNG 或 WebP 图片');input.value='';return}if(file.size>10*1024*1024){ElMessage.error('商品主图不能超过 10MB');input.value='';return}uploading.value=true;try{const data=new FormData();data.append('file',file);form.mainImage=(await api.post<ApiResponse<{url:string}>>('/admin/files/product-images',data)).data.data.url;ElMessage.success('商品主图上传成功')}catch{ElMessage.error('商品主图上传失败，请重试')}finally{uploading.value=false;input.value=''}}
function onEditorReady(instance:any){quill.value=instance}
function chooseRichImage(){if(!uploadingRichImage.value)richImageInput.value?.click()}
async function uploadRichImage(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){ElMessage.error('详情图片仅支持 JPG、PNG 或 WebP');input.value='';return}if(file.size>10*1024*1024){ElMessage.error('详情图片不能超过 10MB');input.value='';return}uploadingRichImage.value=true;try{const data=new FormData();data.append('file',file);const response=await api.post<ApiResponse<{url:string}>>('/admin/files/richtext-images',data);const url=response.data.data?.url;if(!url)throw new Error('上传结果缺少图片地址');try{const editor=quill.value;if(!editor)throw new Error('编辑器未就绪');const range=editor.getSelection()??{index:Math.max(0,editor.getLength()-1),length:0};editor.insertEmbed(range.index,'image',url,'user');editor.setSelection(range.index+1,0,'silent')}catch{form.detailHtml=`${form.detailHtml||''}<p><img src="${url}" alt="商品详情图"></p>`;ElMessage.warning('图片已上传并添加到详情末尾');return}ElMessage.success('详情图片已插入')}catch(error){ElMessage.error(error instanceof Error?error.message:'详情图片上传失败，请重试')}finally{uploadingRichImage.value=false;input.value=''}}
async function save(){const payload={id:form.id,name:form.name,subtitle:form.subtitle,categoryId:form.categoryId,mainImage:form.mainImage,detailHtml:form.detailHtml,minPrice:form.minPrice,sales:form.sales??0,published:form.published};const{data}=form.id?await api.put<ApiResponse<Product>>(`/admin/products/${form.id}`,payload):await api.post<ApiResponse<Product>>('/admin/products',payload);if(!form.id&&form.skuPrice>0)await api.post('/admin/skus',{productId:data.data.id,specJson:form.skuSpec||'{}',price:form.skuPrice,stock:form.skuStock,enabled:true});dialog.value=false;ElMessage.success('商品已保存');load()}onMounted(load)
</script>
<template>
  <div class="panel">
    <div class="toolbar"><h2>商品管理</h2><div><el-input v-model="keyword" placeholder="搜索商品" clearable style="width:210px" @keyup.enter="search"/><el-button @click="search">查询</el-button><el-button type="primary" @click="edit()">新建商品</el-button></div></div>
    <el-table :data="rows">
      <el-table-column prop="id" label="商品ID" width="100"/>
      <el-table-column label="商品" min-width="230"><template #default="scope"><div style="display:flex;align-items:center;gap:10px"><el-image :src="scope.row.mainImage" style="width:54px;height:54px;border-radius:8px" fit="cover"/><div><b>{{scope.row.name}}</b><div style="color:#829ab0">{{scope.row.subtitle}}</div></div></div></template></el-table-column>
      <el-table-column prop="categoryId" label="分类ID"/><el-table-column label="价格"><template #default="scope">¥{{scope.row.minPrice}}</template></el-table-column><el-table-column prop="sales" label="销量"/><el-table-column label="状态"><template #default="scope"><el-tag :type="scope.row.published?'success':'info'">{{scope.row.published?'已上架':'已下架'}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="scope"><el-button link type="primary" @click="edit(scope.row)">编辑</el-button></template></el-table-column>
    </el-table>
    <el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" :page-sizes="[10,20,50,100]" layout="total, sizes, prev, pager, next, jumper" style="margin-top:18px;justify-content:flex-end" @current-change="load" @size-change="search"/>
  </div>
  <el-dialog v-model="dialog" :title="form.id?'编辑商品':'新建商品'" width="820"><el-form label-width="90"><div class="product-form-grid"><el-form-item label="商品名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="商品分类"><el-select v-model="form.categoryId" style="width:100%"><el-option v-for="category in categories" :key="category.id" :label="category.name" :value="category.id"/></el-select></el-form-item><el-form-item label="副标题" class="full-row"><el-input v-model="form.subtitle"/></el-form-item><el-form-item label="商品主图" class="full-row"><div class="main-image-field"><div class="main-image-actions"><el-input v-model="form.mainImage" placeholder="图片地址或本地上传"/><el-button type="primary" plain :loading="uploading" @click="chooseMainImage">选择本地图片</el-button><input ref="mainImageInput" class="file-input" type="file" accept="image/jpeg,image/png,image/webp" @change="uploadMainImage"></div><el-image v-if="form.mainImage" :src="form.mainImage" fit="cover" class="main-image-preview"><template #error><div class="preview-error">图片无法加载</div></template></el-image></div></el-form-item><el-form-item label="起售价"><el-input-number v-model="form.minPrice" :precision="2"/></el-form-item><el-form-item label="是否上架"><el-switch v-model="form.published"/></el-form-item><template v-if="!form.id"><el-form-item label="SKU规格"><el-input v-model="form.skuSpec" placeholder='{"color":"蓝色"}'/></el-form-item><el-form-item label="SKU价格"><el-input-number v-model="form.skuPrice" :precision="2"/></el-form-item><el-form-item label="SKU库存"><el-input-number v-model="form.skuStock"/></el-form-item></template></div><el-form-item label="商品详情"><div class="detail-editor"><QuillEditor v-model:content="form.detailHtml" content-type="html" :options="editorOptions" @ready="onEditorReady"/><input ref="richImageInput" class="file-input" type="file" accept="image/jpeg,image/png,image/webp" @change="uploadRichImage"><div v-if="uploadingRichImage" class="editor-uploading">图片上传中…</div></div></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存商品</el-button></template></el-dialog>
</template>
<style scoped>.product-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.full-row{grid-column:1/-1}.main-image-field{width:100%}.main-image-actions{display:flex;gap:10px;width:100%}.main-image-actions .el-input{flex:1}.file-input{display:none}.main-image-preview{display:block;width:180px;height:120px;margin-top:10px;border-radius:9px;background:#f4f7fb}.preview-error{height:100%;display:grid;place-items:center;color:#829ab0;font-size:12px}.detail-editor{position:relative;width:100%;padding-bottom:45px}.detail-editor :deep(.ql-container){height:240px}.detail-editor :deep(.ql-editor img){max-width:100%;height:auto}.editor-uploading{position:absolute;right:12px;top:7px;color:#409eff;font-size:12px}</style>
