<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{api,type ApiResponse}from'@whaashop/shared';
interface User{id:number;username:string;email?:string;nickname:string;avatarUrl?:string;bio?:string;role:'ADMIN'|'USER';enabled:boolean;createdAt:string}interface Page<T>{items:T[];total:number}
const rows=ref<User[]>([]),keyword=ref(''),page=ref(1),size=ref(20),total=ref(0),dialog=ref(false),saving=ref(false);const form=reactive<{id?:number;username:string;email:string;password:string;nickname:string;role:'ADMIN'|'USER';enabled:boolean}>({username:'',email:'',password:'',nickname:'',role:'USER',enabled:true});
async function load(){const{data}=await api.get<ApiResponse<Page<User>>>('/admin/users',{params:{keyword:keyword.value,page:page.value,size:size.value}});rows.value=data.data.items;total.value=data.data.total}function search(){page.value=1;load()}
function openCreate(){Object.assign(form,{id:undefined,username:'',email:'',password:'',nickname:'',role:'USER',enabled:true});dialog.value=true}function openEdit(user:User){Object.assign(form,{id:user.id,username:user.username,email:user.email||'',password:'',nickname:user.nickname,role:user.role,enabled:user.enabled});dialog.value=true}
async function save(){if(form.username.trim().length<3)return ElMessage.warning('用户名至少 3 个字符');if(!/^\S+@\S+\.\S+$/.test(form.email))return ElMessage.warning('请输入正确的邮箱');if(!form.id&&form.password.length<6)return ElMessage.warning('密码至少 6 个字符');if(form.id&&form.password&&form.password.length<6)return ElMessage.warning('新密码至少 6 个字符');if(!form.nickname.trim())return ElMessage.warning('请输入昵称');saving.value=true;try{form.id?await api.put(`/admin/users/${form.id}`,form):await api.post('/admin/users',form);dialog.value=false;ElMessage.success(form.id?'用户已更新':'用户已新增');if(!form.id)page.value=1;load()}finally{saving.value=false}}
async function remove(user:User){await ElMessageBox.confirm(`确认删除用户“${user.nickname}”？已有业务数据的用户将无法删除。`,'删除用户',{type:'warning',confirmButtonText:'确认删除',cancelButtonText:'取消'});await api.delete(`/admin/users/${user.id}`);ElMessage.success('用户已删除');if(rows.value.length===1&&page.value>1)page.value--;load()}
async function status(user:User){await api.patch(`/admin/users/${user.id}/status`,null,{params:{enabled:user.enabled}});ElMessage.success('状态已更新')}async function role(user:User){await api.patch(`/admin/users/${user.id}/role`,null,{params:{role:user.role}});ElMessage.success('角色已更新')}onMounted(load)
</script>
<template><div class="panel"><div class="toolbar"><h2>用户管理</h2><div><el-input v-model="keyword" placeholder="用户名或昵称" clearable style="width:220px" @keyup.enter="search"/><el-button @click="search">查询</el-button><el-button type="primary" @click="openCreate">新增用户</el-button></div></div><el-table :data="rows"><el-table-column label="用户" min-width="190"><template #default="s"><div class="user-cell"><el-avatar :src="s.row.avatarUrl">{{s.row.nickname?.[0]}}</el-avatar><div><b>{{s.row.nickname}}</b><div>@{{s.row.username}}</div></div></div></template></el-table-column><el-table-column prop="email" label="邮箱" min-width="210"><template #default="s">{{s.row.email||'未绑定'}}</template></el-table-column><el-table-column prop="bio" label="简介" min-width="160" show-overflow-tooltip/><el-table-column label="角色" width="130"><template #default="s"><el-select v-model="s.row.role" @change="role(s.row)"><el-option label="管理员" value="ADMIN"/><el-option label="普通用户" value="USER"/></el-select></template></el-table-column><el-table-column label="启用" width="100"><template #default="s"><el-switch v-model="s.row.enabled" @change="status(s.row)"/></template></el-table-column><el-table-column prop="createdAt" label="注册时间" width="190"/><el-table-column label="操作" width="150" fixed="right"><template #default="s"><el-button link type="primary" @click="openEdit(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next, jumper" class="pager" @current-change="load" @size-change="search"/></div>
<el-dialog v-model="dialog" :title="form.id?'编辑用户':'新增用户'" width="500"><el-form label-width="90px"><el-form-item label="用户名" required><el-input v-model="form.username" maxlength="30" placeholder="3-30 个字符"/></el-form-item><el-form-item label="邮箱" required><el-input v-model="form.email" maxlength="120" placeholder="用于密码找回"/></el-form-item><el-form-item :label="form.id?'重置密码':'初始密码'" :required="!form.id"><el-input v-model="form.password" type="password" show-password maxlength="64" :placeholder="form.id?'留空表示不修改密码':'至少 6 个字符'"/></el-form-item><el-form-item label="昵称" required><el-input v-model="form.nickname" maxlength="50"/></el-form-item><el-form-item label="角色"><el-radio-group v-model="form.role"><el-radio value="USER">普通用户</el-radio><el-radio value="ADMIN">管理员</el-radio></el-radio-group></el-form-item><el-form-item label="启用状态"><el-switch v-model="form.enabled"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">{{form.id?'保存修改':'确认新增'}}</el-button></template></el-dialog></template>
<style scoped>.user-cell{display:flex;align-items:center;gap:10px}.user-cell div div{color:#829ab0}.pager{margin-top:18px;justify-content:flex-end}</style>
