ALTER TABLE shop_user
 ADD COLUMN avatar_url VARCHAR(500) NULL AFTER nickname,
 ADD COLUMN bio VARCHAR(300) NULL AFTER avatar_url,
 ADD COLUMN gender VARCHAR(16) NOT NULL DEFAULT 'UNSPECIFIED' AFTER bio,
 ADD COLUMN birthday DATE NULL AFTER gender;

