<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, type ApiResponse, type Product } from '@whaashop/shared'
interface ProductPage { items: Product[]; total: number; page: number; size: number }
const route=useRoute(),router=useRouter(),products=ref<Product[]>([]),total=ref(0),loading=ref(false),error=ref(''),size=12
const keyword=computed(()=>String(route.query.q??'').trim()),page=computed(()=>Math.max(1,Number(route.query.page)||1)),pageCount=computed(()=>Math.max(1,Math.ceil(total.value/size)))
async function load(){if(!keyword.value){products.value=[];total.value=0;return}loading.value=true;error.value='';try{const{data}=await api.get<ApiResponse<ProductPage>>('/shop/products',{params:{keyword:keyword.value,page:page.value,size}});products.value=data.data.items;total.value=data.data.total;if(page.value>pageCount.value)changePage(pageCount.value)}catch(e){error.value=e instanceof Error?e.message:'搜索失败，请稍后重试'}finally{loading.value=false}}
function changePage(target:number){if(target<1||target>pageCount.value||target===page.value)return;router.push({path:'/search',query:{q:keyword.value,...(target>1?{page:target}:{})}});window.scrollTo({top:0,behavior:'smooth'})}
watch(()=>[route.query.q,route.query.page],load,{immediate:true})
</script>
<template><div class="search-page container"><div class="search-heading"><div><span class="eyebrow">SEARCH RESULTS</span><h1>搜索“{{keyword}}”</h1></div><p v-if="!loading&&!error">找到 <b>{{total}}</b> 件相关商品</p></div><div v-if="loading" class="search-loading"><i v-for="n in 8" :key="n"></i></div><div v-else-if="error" class="search-empty"><strong>搜索遇到问题</strong><p>{{error}}</p><button class="btn" @click="load">重新搜索</button></div><div v-else-if="!keyword" class="search-empty"><strong>输入关键词开始搜索</strong><p>可以搜索商品名称或商品描述，例如“耳机”“坚果”。</p></div><div v-else-if="!products.length" class="search-empty"><span>⌕</span><strong>没有找到相关商品</strong><p>换个更简短的关键词试试，或返回商城看看精选商品。</p><router-link class="btn" to="/">返回商城首页</router-link></div><div v-else class="grid product-grid search-results"><router-link v-for="p in products" :key="p.id" :to="`/products/${p.id}`" class="product"><div class="product-image"><img :src="p.mainImage" :alt="p.name"><span>搜索结果</span></div><div class="product-body"><h3>{{p.name}}</h3><p class="muted">{{p.subtitle}}</p><div class="product-meta"><span class="price">¥{{p.minPrice}}</span><small>已售 {{p.sales}}</small></div></div></router-link></div><div v-if="!loading&&products.length&&pageCount>1" class="search-pagination"><button :disabled="page===1" @click="changePage(page-1)">上一页</button><span>第 {{page}} / {{pageCount}} 页</span><button :disabled="page===pageCount" @click="changePage(page+1)">下一页</button></div></div></template>
