package com.whaa.shop.promotion.application;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.whaa.shop.common.api.PageResponse;import com.whaa.shop.common.exception.BusinessException;import com.whaa.shop.product.domain.*;import com.whaa.shop.product.infrastructure.*;import com.whaa.shop.promotion.domain.FlashSale;import com.whaa.shop.promotion.infrastructure.FlashSaleMapper;import com.whaa.shop.recommendation.domain.Recommendation;import com.whaa.shop.recommendation.infrastructure.RecommendationMapper;import org.springframework.stereotype.Service;import java.math.BigDecimal;import java.time.LocalDateTime;import java.util.*;
@Service public class PromotionService {private final FlashSaleMapper flashes;private final RecommendationMapper recommendations;private final ProductMapper products;private final SkuMapper skus;public PromotionService(FlashSaleMapper f,RecommendationMapper r,ProductMapper p,SkuMapper s){flashes=f;recommendations=r;products=p;skus=s;}
 public PageResponse<RecommendationView> recommendations(long page,long size){Page<Recommendation> p=recommendations.selectPage(Page.of(page,size),new LambdaQueryWrapper<Recommendation>().orderByAsc(Recommendation::getPositionCode).orderByAsc(Recommendation::getSortOrder));return new PageResponse<>(p.getRecords().stream().map(this::view).toList(),p.getTotal(),page,size);}
 public PageResponse<FlashSaleView> flashes(long page,long size){Page<FlashSale> p=flashes.selectPage(Page.of(page,size),new LambdaQueryWrapper<FlashSale>().orderByDesc(FlashSale::getStartAt));return new PageResponse<>(p.getRecords().stream().map(this::view).toList(),p.getTotal(),page,size);}
 public Recommendation save(Recommendation value){Product p=value.getProductId()==null?null:products.selectById(value.getProductId());if(p==null)throw new BusinessException("请选择有效商品");if(value.getPositionCode()==null||!Set.of("HOME_FEATURED","HOME_NEW").contains(value.getPositionCode()))throw new BusinessException("推荐位置无效");if(value.getSortOrder()==null)value.setSortOrder(0);if(value.getEnabled()==null)value.setEnabled(true);if(value.getId()==null)recommendations.insert(value);else recommendations.updateById(value);return value;}
 public FlashSale save(FlashSale value){Sku sku=value.getSkuId()==null?null:skus.selectById(value.getSkuId());if(sku==null||products.selectById(sku.getProductId())==null)throw new BusinessException("请选择有效的商品规格");if(value.getPrice()==null||value.getPrice().signum()<=0||value.getPrice().compareTo(sku.getPrice())>=0)throw new BusinessException("秒杀价必须大于0且低于商品原价");if(value.getStock()==null||value.getStock()<=0||value.getStock()>sku.getStock())throw new BusinessException("活动库存必须大于0且不能超过SKU库存");if(value.getStartAt()==null||value.getEndAt()==null||!value.getEndAt().isAfter(value.getStartAt()))throw new BusinessException("活动时间范围无效");if(value.getPerUserLimit()==null||value.getPerUserLimit()<=0)value.setPerUserLimit(1);if(value.getEnabled()==null)value.setEnabled(false);if(value.getId()==null)flashes.insert(value);else flashes.updateById(value);return value;}
 public List<RecommendationView> shopRecommendations(String position){return recommendations.selectList(new LambdaQueryWrapper<Recommendation>().eq(Recommendation::getEnabled,true).eq(Recommendation::getPositionCode,position).orderByAsc(Recommendation::getSortOrder).last("LIMIT 8")).stream().map(this::view).filter(v->v.productId()!=null&&Boolean.TRUE.equals(v.published())).toList();}
 public List<FlashSaleView> activeFlashes(){LocalDateTime now=LocalDateTime.now();return flashes.selectList(new LambdaQueryWrapper<FlashSale>().eq(FlashSale::getEnabled,true).le(FlashSale::getStartAt,now).gt(FlashSale::getEndAt,now).gt(FlashSale::getStock,0).orderByAsc(FlashSale::getEndAt).last("LIMIT 8")).stream().map(this::view).filter(v->v.productId()!=null&&Boolean.TRUE.equals(v.published())).toList();}
 public PriceQuote price(Long skuId){LocalDateTime now=LocalDateTime.now();FlashSale sale=flashes.selectOne(new LambdaQueryWrapper<FlashSale>().eq(FlashSale::getSkuId,skuId).eq(FlashSale::getEnabled,true).le(FlashSale::getStartAt,now).gt(FlashSale::getEndAt,now).gt(FlashSale::getStock,0).last("LIMIT 1"));Sku sku=skus.selectById(skuId);if(sku==null)return new PriceQuote(null,BigDecimal.ZERO,Integer.MAX_VALUE);return sale==null?new PriceQuote(null,sku.getPrice(),Integer.MAX_VALUE):new PriceQuote(sale.getId(),sale.getPrice(),sale.getPerUserLimit());}
 public void deductFlash(Long flashId,int quantity){if(flashId!=null&&flashes.deduct(flashId,quantity)!=1)throw new BusinessException("秒杀活动库存不足或已经结束");}
 public void deleteRecommendation(Long id){recommendations.deleteById(id);}public void deleteFlash(Long id){flashes.deleteById(id);}
 private RecommendationView view(Recommendation r){Product p=products.selectById(r.getProductId());return new RecommendationView(r.getId(),r.getProductId(),p==null?null:p.getName(),p==null?null:p.getMainImage(),p==null?null:p.getSubtitle(),p==null?null:p.getMinPrice(),p==null?null:p.getPublished(),r.getPositionCode(),r.getSortOrder(),r.getEnabled());}
 private FlashSaleView view(FlashSale f){Sku s=skus.selectById(f.getSkuId());Product p=s==null?null:products.selectById(s.getProductId());return new FlashSaleView(f.getId(),f.getSkuId(),s==null?null:s.getProductId(),p==null?null:p.getName(),p==null?null:p.getMainImage(),s==null?null:s.getSpecJson(),s==null?null:s.getPrice(),p==null?null:p.getPublished(),f.getPrice(),f.getStock(),f.getPerUserLimit(),f.getStartAt(),f.getEndAt(),f.getEnabled());}
 public record RecommendationView(Long id,Long productId,String productName,String productImage,String subtitle,BigDecimal price,Boolean published,String positionCode,Integer sortOrder,Boolean enabled){}
 public record FlashSaleView(Long id,Long skuId,Long productId,String productName,String productImage,String skuSpec,BigDecimal originalPrice,Boolean published,BigDecimal price,Integer stock,Integer perUserLimit,LocalDateTime startAt,LocalDateTime endAt,Boolean enabled){}
 public record PriceQuote(Long flashId,BigDecimal price,Integer perUserLimit){}
}
