package com.whaa.shop.order.application;
import com.whaa.shop.cart.domain.CartItem;import com.whaa.shop.cart.infrastructure.CartItemMapper;import com.whaa.shop.common.exception.BusinessException;import com.whaa.shop.order.domain.*;import com.whaa.shop.order.infrastructure.*;import com.whaa.shop.product.domain.*;import com.whaa.shop.product.infrastructure.*;import com.whaa.shop.promotion.application.PromotionService;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.LocalDateTime;import java.util.*;
@Service public class CheckoutService {private final CartItemMapper carts;private final SkuMapper skus;private final ProductMapper products;private final OrderMapper orders;private final OrderItemMapper items;private final PromotionService promotions;public CheckoutService(CartItemMapper c,SkuMapper s,ProductMapper p,OrderMapper o,OrderItemMapper i,PromotionService promotions){carts=c;skus=s;products=p;orders=o;items=i;this.promotions=promotions;}
 @Transactional public ShopOrder create(long uid,List<Long> cartIds,String name,String phone,String address){
  if(cartIds==null||cartIds.isEmpty())throw new BusinessException("请选择结算商品");if(name==null||name.isBlank()||phone==null||phone.isBlank()||address==null||address.isBlank())throw new BusinessException("请填写完整收货信息");
  List<Line> lines=new ArrayList<>();BigDecimal total=BigDecimal.ZERO;
  for(Long id:cartIds){CartItem cart=carts.selectById(id);if(cart==null||!cart.getUserId().equals(uid)||!Boolean.TRUE.equals(cart.getChecked()))throw new BusinessException("购物车数据无效");Sku sku=skus.selectById(cart.getSkuId());Product product=sku==null?null:products.selectById(sku.getProductId());if(sku==null||product==null||!Boolean.TRUE.equals(product.getPublished()))throw new BusinessException("商品已失效");var quote=promotions.price(sku.getId());if(cart.getQuantity()>quote.perUserLimit())throw new BusinessException("商品超过秒杀限购数量");if(skus.deduct(sku.getId(),cart.getQuantity())!=1)throw new BusinessException("商品库存不足");promotions.deductFlash(quote.flashId(),cart.getQuantity());lines.add(new Line(cart,sku,product,quote.price()));total=total.add(quote.price().multiply(BigDecimal.valueOf(cart.getQuantity())));}
  ShopOrder order=new ShopOrder();order.setOrderNo("WS"+java.time.format.DateTimeFormatter.ofPattern("yyyyMMddHHmmss").format(LocalDateTime.now())+String.format("%04d",new Random().nextInt(10000)));order.setUserId(uid);order.setStatus(OrderStatus.PENDING_PAYMENT);order.setTotalAmount(total);order.setReceiverName(name);order.setReceiverPhone(phone);order.setReceiverAddress(address);order.setCreatedAt(LocalDateTime.now());order.setVersion(0);orders.insert(order);
  for(Line line:lines){OrderItem item=new OrderItem();item.setOrderId(order.getId());item.setProductId(line.product.getId());item.setSkuId(line.sku.getId());item.setProductName(line.product.getName());item.setSkuSpec(line.sku.getSpecJson());item.setProductImage(line.product.getMainImage());item.setUnitPrice(line.price);item.setQuantity(line.cart.getQuantity());item.setReviewed(false);items.insert(item);carts.deleteById(line.cart.getId());}return order;
 }
 @Transactional public ShopOrder buyNow(long uid,Long skuId,int quantity,String name,String phone,String address){if(skuId==null||quantity<1)throw new BusinessException("请选择商品规格和数量");if(name==null||name.isBlank()||phone==null||phone.isBlank()||address==null||address.isBlank())throw new BusinessException("请选择完整收货地址");Sku sku=skus.selectById(skuId);Product product=sku==null?null:products.selectById(sku.getProductId());if(sku==null||!Boolean.TRUE.equals(sku.getEnabled())||product==null||!Boolean.TRUE.equals(product.getPublished()))throw new BusinessException("商品已失效");var quote=promotions.price(skuId);if(quantity>quote.perUserLimit())throw new BusinessException("商品超过秒杀限购数量");if(skus.deduct(skuId,quantity)!=1)throw new BusinessException("商品库存不足");promotions.deductFlash(quote.flashId(),quantity);ShopOrder order=new ShopOrder();order.setOrderNo("WS"+java.time.format.DateTimeFormatter.ofPattern("yyyyMMddHHmmss").format(LocalDateTime.now())+String.format("%04d",new Random().nextInt(10000)));order.setUserId(uid);order.setStatus(OrderStatus.PENDING_PAYMENT);order.setTotalAmount(quote.price().multiply(BigDecimal.valueOf(quantity)));order.setReceiverName(name);order.setReceiverPhone(phone);order.setReceiverAddress(address);order.setCreatedAt(LocalDateTime.now());order.setVersion(0);orders.insert(order);OrderItem item=new OrderItem();item.setOrderId(order.getId());item.setProductId(product.getId());item.setSkuId(sku.getId());item.setProductName(product.getName());item.setSkuSpec(sku.getSpecJson());item.setProductImage(product.getMainImage());item.setUnitPrice(quote.price());item.setQuantity(quantity);item.setReviewed(false);items.insert(item);return order;}
 private record Line(CartItem cart,Sku sku,Product product,BigDecimal price){}
}
