package com.whaa.shop.order.application;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.baomidou.mybatisplus.extension.plugins.pagination.Page; import com.whaa.shop.common.api.PageResponse; import com.whaa.shop.common.exception.BusinessException; import com.whaa.shop.order.domain.*; import com.whaa.shop.order.infrastructure.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.List;
@Service public class OrderService {private final OrderMapper orders;private final OrderItemMapper items;public OrderService(OrderMapper o,OrderItemMapper i){orders=o;items=i;}
 public List<ShopOrder> mine(long userId){return orders.selectList(new LambdaQueryWrapper<ShopOrder>().eq(ShopOrder::getUserId,userId).orderByDesc(ShopOrder::getCreatedAt));}
 public List<ShopOrder> adminList(OrderStatus status){return orders.selectList(new LambdaQueryWrapper<ShopOrder>().eq(status!=null,ShopOrder::getStatus,status).orderByDesc(ShopOrder::getCreatedAt));}
 public PageResponse<ShopOrder> adminPage(OrderStatus status,long page,long size){Page<ShopOrder> result=orders.selectPage(Page.of(page,size),new LambdaQueryWrapper<ShopOrder>().eq(status!=null,ShopOrder::getStatus,status).orderByDesc(ShopOrder::getCreatedAt));return new PageResponse<>(result.getRecords(),result.getTotal(),page,size);}
 public List<OrderItem> items(Long orderId,long userId){ShopOrder o=owned(orderId,userId);return items.selectList(new LambdaQueryWrapper<OrderItem>().eq(OrderItem::getOrderId,o.getId()));}
 @Transactional public void ship(Long id){ShopOrder o=require(id);if(o.getStatus()==OrderStatus.SHIPPED)return;if(o.getStatus()!=OrderStatus.PAID||orders.transition(id,"PAID","SHIPPED",LocalDateTime.now())!=1)throw new BusinessException("只有已支付订单可以发货");}
 @Transactional public void confirm(Long id,long userId){ShopOrder o=owned(id,userId);if(o.getStatus()==OrderStatus.COMPLETED)return;if(o.getStatus()!=OrderStatus.SHIPPED||orders.transition(id,"SHIPPED","COMPLETED",LocalDateTime.now())!=1)throw new BusinessException("只有已发货订单可以确认收货");}
 @Transactional public boolean markPaid(String orderNo,java.math.BigDecimal amount){ShopOrder o=orders.selectOne(new LambdaQueryWrapper<ShopOrder>().eq(ShopOrder::getOrderNo,orderNo));if(o==null)return false;if(o.getStatus()==OrderStatus.PAID||o.getStatus()==OrderStatus.SHIPPED||o.getStatus()==OrderStatus.COMPLETED)return o.getTotalAmount().compareTo(amount)==0;return orders.markPaid(orderNo,amount,LocalDateTime.now())==1;}
 public ShopOrder findByNo(String orderNo){return orders.selectOne(new LambdaQueryWrapper<ShopOrder>().eq(ShopOrder::getOrderNo,orderNo));}
 public ShopOrder findOwnedByNo(String orderNo,long userId){return orders.selectOne(new LambdaQueryWrapper<ShopOrder>().eq(ShopOrder::getOrderNo,orderNo).eq(ShopOrder::getUserId,userId));}
 public ShopOrder require(Long id){ShopOrder o=orders.selectById(id);if(o==null)throw new BusinessException("订单不存在");return o;} public ShopOrder owned(Long id,long uid){ShopOrder o=require(id);if(!o.getUserId().equals(uid))throw new BusinessException("无权访问该订单");return o;}}
