package com.whaa.shop.user.controller;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.whaa.shop.common.api.*;import com.whaa.shop.common.exception.BusinessException;import com.whaa.shop.user.application.UserAdminService;import com.whaa.shop.user.domain.User;import com.whaa.shop.user.infrastructure.UserMapper;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.web.bind.annotation.*;import java.time.*;
@RestController @RequestMapping("/api/v1/admin/users") public class UserAdminController {private final UserMapper users;private final UserAdminService service;public UserAdminController(UserMapper users,UserAdminService service){this.users=users;this.service=service;}
 @GetMapping ApiResponse<PageResponse<UserView>> page(@RequestParam(defaultValue="1")long page,@RequestParam(defaultValue="20")long size,@RequestParam(required=false)String keyword){var q=new LambdaQueryWrapper<User>().and(keyword!=null&&!keyword.isBlank(),w->w.like(User::getUsername,keyword).or().like(User::getNickname,keyword)).orderByDesc(User::getCreatedAt);Page<User> p=users.selectPage(Page.of(page,size),q);return ApiResponse.ok(new PageResponse<>(p.getRecords().stream().map(this::view).toList(),p.getTotal(),page,size));}
 @PostMapping ApiResponse<UserView> create(@Valid @RequestBody CreateUser request){return ApiResponse.ok(view(service.create(request.username(),request.email(),request.password(),request.nickname(),request.role(),request.enabled())));}
 @PutMapping("/{id}")ApiResponse<UserView> update(@PathVariable Long id,@Valid @RequestBody UpdateUser request){return ApiResponse.ok(view(service.update(id,request.username(),request.email(),request.password(),request.nickname(),request.role(),request.enabled())));}
 @DeleteMapping("/{id}")ApiResponse<Void> delete(@PathVariable Long id){service.delete(id);return ApiResponse.ok();}
 @PatchMapping("/{id}/status")ApiResponse<Void> status(@PathVariable Long id,@RequestParam boolean enabled){User u=require(id);u.setEnabled(enabled);users.updateById(u);return ApiResponse.ok();}
 @PatchMapping("/{id}/role")ApiResponse<Void> role(@PathVariable Long id,@RequestParam String role){if(!role.equals("ADMIN")&&!role.equals("USER"))throw new BusinessException("角色无效");User u=require(id);u.setRole(role);users.updateById(u);return ApiResponse.ok();}
 private User require(Long id){User u=users.selectById(id);if(u==null)throw new BusinessException("用户不存在");return u;}private UserView view(User u){return new UserView(u.getId(),u.getUsername(),u.getEmail(),u.getNickname(),u.getAvatarUrl(),u.getBio(),u.getGender(),u.getBirthday(),u.getRole(),u.getEnabled(),u.getCreatedAt());}
 public record CreateUser(@Size(min=3,max=30)String username,@Email @NotBlank String email,@Size(min=6,max=64)String password,@NotBlank @Size(max=50)String nickname,@Pattern(regexp="ADMIN|USER")String role,boolean enabled){}public record UpdateUser(@Size(min=3,max=30)String username,@Email @NotBlank String email,String password,@NotBlank @Size(max=50)String nickname,@Pattern(regexp="ADMIN|USER")String role,boolean enabled){}public record UserView(Long id,String username,String email,String nickname,String avatarUrl,String bio,String gender,LocalDate birthday,String role,Boolean enabled,LocalDateTime createdAt){}
}
