package com.whaa.shop.file.controller;
import com.whaa.shop.common.api.ApiResponse;import com.whaa.shop.common.exception.BusinessException;import com.whaa.shop.file.application.ObjectStorageService;import org.springframework.core.io.InputStreamResource;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.time.Duration;import java.util.Set;
@RestController public class FileController {
 private static final Set<String> PUBLIC_IMAGE_PREFIXES=Set.of("avatars/","reviews/","richtext/","banners/","products/");private final ObjectStorageService storage;public FileController(ObjectStorageService s){storage=s;}
 @PostMapping("/api/v1/shop/files/review-images")ApiResponse<ObjectStorageService.StoredObject> review(@RequestParam MultipartFile file){return ApiResponse.ok(storage.upload("reviews",file));}@PostMapping("/api/v1/admin/files/richtext-images")ApiResponse<ObjectStorageService.StoredObject> rich(@RequestParam MultipartFile file){return ApiResponse.ok(storage.upload("richtext",file));}@PostMapping("/api/v1/admin/files/banner-images")ApiResponse<ObjectStorageService.StoredObject> banner(@RequestParam MultipartFile file){return ApiResponse.ok(storage.upload("banners",file));}@PostMapping("/api/v1/admin/files/product-images")ApiResponse<ObjectStorageService.StoredObject> product(@RequestParam MultipartFile file){return ApiResponse.ok(storage.upload("products",file));}
 @GetMapping("/api/v1/files/{*objectKey}")ResponseEntity<InputStreamResource> publicImage(@PathVariable String objectKey){String key=normalize(objectKey);if(PUBLIC_IMAGE_PREFIXES.stream().noneMatch(key::startsWith))throw new BusinessException("文件不可公开访问");return ResponseEntity.ok().contentType(imageType(key)).cacheControl(CacheControl.maxAge(Duration.ofDays(30)).cachePublic()).body(new InputStreamResource(storage.read(key)));}
 private String normalize(String value){String key=value==null?"":value.replace('\\','/').replaceFirst("^/+","");if(key.isBlank()||key.contains(".."))throw new BusinessException("文件路径无效");return key;}
 private MediaType imageType(String key){String value=key.toLowerCase();if(value.endsWith(".jpg")||value.endsWith(".jpeg"))return MediaType.IMAGE_JPEG;if(value.endsWith(".png"))return MediaType.IMAGE_PNG;if(value.endsWith(".webp"))return MediaType.parseMediaType("image/webp");throw new BusinessException("仅支持访问公开图片");}
}
