package com.whaa.shop.review.application;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.fasterxml.jackson.databind.ObjectMapper;import com.whaa.shop.common.api.PageResponse;import com.whaa.shop.common.exception.BusinessException;import com.whaa.shop.order.domain.*;import com.whaa.shop.order.infrastructure.OrderItemMapper;import com.whaa.shop.order.application.OrderService;import com.whaa.shop.review.domain.*;import com.whaa.shop.review.infrastructure.*;import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service public class ReviewService {private static final Logger log=LoggerFactory.getLogger(ReviewService.class);private final ReviewMapper reviews;private final ReviewAppendMapper appends;private final OrderItemMapper items;private final OrderService orders;private final ObjectMapper json;public ReviewService(ReviewMapper r,ReviewAppendMapper a,OrderItemMapper i,OrderService o,ObjectMapper j){reviews=r;appends=a;items=i;orders=o;json=j;}
 @Transactional public ProductReview create(long uid,Long itemId,int rating,String content,List<String> images){if(rating<1||rating>5)throw new BusinessException("评分必须为1到5星");validate(content,images);OrderItem item=items.selectById(itemId);if(item==null)throw new BusinessException("订单项不存在");ShopOrder order=orders.owned(item.getOrderId(),uid);if(order.getStatus()!=OrderStatus.COMPLETED)throw new BusinessException("确认收货后才能评价");if(items.markReviewed(itemId)!=1)throw new BusinessException("该商品已经评价");ProductReview r=new ProductReview();r.setOrderItemId(itemId);r.setProductId(item.getProductId());r.setUserId(uid);r.setRating(rating);r.setContent(content);r.setImagesJson(write(images));r.setAppendCount(0);r.setHidden(false);r.setCreatedAt(LocalDateTime.now());reviews.insert(r);return r;}
 @Transactional public ReviewAppend append(long uid,Long reviewId,String content,List<String> images){validate(content,images);if(reviews.reserveAppend(reviewId,uid)!=1)throw new BusinessException("追评不存在、无权限或已达到三次上限");ProductReview r=reviews.selectById(reviewId);ReviewAppend a=new ReviewAppend();a.setReviewId(reviewId);a.setSequenceNo(r.getAppendCount());a.setContent(content);a.setImagesJson(write(images));a.setCreatedAt(LocalDateTime.now());appends.insert(a);return a;}
 public PageResponse<ProductReview> page(Long productId,int rating,boolean withImages,long page,long size){var q=new LambdaQueryWrapper<ProductReview>().eq(ProductReview::getProductId,productId).eq(ProductReview::getHidden,false).eq(rating>0,ProductReview::getRating,rating).ne(withImages,ProductReview::getImagesJson,"[]").orderByDesc(ProductReview::getCreatedAt);Page<ProductReview> p=reviews.selectPage(Page.of(page,size),q);return new PageResponse<>(p.getRecords(),p.getTotal(),page,size);}
 public PageResponse<ProductReview> adminPage(Long productId,Long userId,int rating,long page,long size){var q=new LambdaQueryWrapper<ProductReview>().eq(productId!=null,ProductReview::getProductId,productId).eq(userId!=null,ProductReview::getUserId,userId).eq(rating>0,ProductReview::getRating,rating).orderByDesc(ProductReview::getCreatedAt);Page<ProductReview> p=reviews.selectPage(Page.of(page,size),q);return new PageResponse<>(p.getRecords(),p.getTotal(),page,size);}
 public List<ReviewView> mine(long userId){return reviews.selectList(new LambdaQueryWrapper<ProductReview>().eq(ProductReview::getUserId,userId).orderByDesc(ProductReview::getCreatedAt)).stream().map(r->new ReviewView(r,appends.selectList(new LambdaQueryWrapper<ReviewAppend>().eq(ReviewAppend::getReviewId,r.getId()).orderByAsc(ReviewAppend::getSequenceNo)))).toList();}
 public Stats stats(Long productId){List<ProductReview> list=reviews.selectList(new LambdaQueryWrapper<ProductReview>().eq(ProductReview::getProductId,productId).eq(ProductReview::getHidden,false));double avg=list.stream().mapToInt(ProductReview::getRating).average().orElse(0);Map<Integer,Long> counts=new TreeMap<>();for(int i=1;i<=5;i++){int star=i;counts.put(i,list.stream().filter(r->r.getRating()==star).count());}return new Stats(list.size(),Math.round(avg*10)/10.0,counts);}
 public void hidden(Long id,boolean hidden){ProductReview r=reviews.selectById(id);if(r==null)throw new BusinessException("评价不存在");r.setHidden(hidden);reviews.updateById(r);}private void validate(String c,List<String> imgs){if(c==null||c.isBlank()||c.length()>2000)throw new BusinessException("评价内容长度应为1到2000字");if(imgs!=null&&imgs.size()>9)throw new BusinessException("最多上传9张图片");}private String write(List<String> v){try{return json.writeValueAsString(v==null?List.of():v);}catch(Exception e){log.error("Failed to serialize review image data: imageCount={}",v==null?0:v.size(),e);throw new BusinessException("图片数据无效");}}public record Stats(long total,double average,Map<Integer,Long> stars){}public record ReviewView(ProductReview review,List<ReviewAppend> appends){}
}
